-- ========== GENERATED BY StoryBit Editor (Ctrl-Alt-E) DO NOT EDIT MANUALLY! ==========

--- Defines a StoryBit object for a test scenario in the Jagged Alliance 3 game.
---
--- The StoryBit object represents a narrative event or scenario that can occur during the game.
--- This particular StoryBit is used for testing purposes and is not intended to be enabled in the final game.
---
--- @field Category string The category this StoryBit belongs to.
--- @field Comment string A comment describing the purpose of this StoryBit.
--- @field EnableChance number The chance (0-100) that this StoryBit will be enabled.
--- @field Enabled boolean Whether this StoryBit is currently enabled.
--- @field ExpirationTime number The time (in milliseconds) after which this StoryBit will expire.
--- @field PopupFxAction string The action to be performed when this StoryBit is triggered.
--- @field ScriptDone boolean Whether the script for this StoryBit has been completed.
--- @field group string The group this StoryBit belongs to.
--- @field id string The unique identifier for this StoryBit.
--- @field qa_info table Information about the modifications made to this StoryBit.
PlaceObj('StoryBit', {
	Category = "",
	Comment = "Added here to be used in the test harness of classes, defined in Common",
	EnableChance = 0,
	Enabled = true,
	ExpirationTime = 40000,
	PopupFxAction = "MessagePopup",
	ScriptDone = true,
	group = "Default",
	id = "TestStoryBit",
	qa_info = PlaceObj('PresetQAInfo', {
		data = {
			{
				action = "Modified",
				time = 1618239324,
				user = "Vihar",
			},
			{
				action = "Modified",
				time = 1665415594,
				user = "Xaerial",
			},
		},
	}),
	save_in = "Common",
})

