---
--- Defines a character effect that grants an additional action point to the target unit at the start of each turn.
---
--- @class AI_StatusEachTurn
--- @field object_class string The class of the object this effect is applied to.
--- @field unit_reactions table A table of unit reactions, including a reaction to the "OnBeginTurn" event that adds the "AI_AdditionalAP" status effect to the target.
-- ========== GENERATED BY CharacterEffectCompositeDef Editor DO NOT EDIT MANUALLY! ==========
UndefineClass('AI_StatusEachTurn')
DefineClass.AI_StatusEachTurn = {__parents={"Perk"}, __generated_by_class="CharacterEffectCompositeDef",

    object_class="Perk", unit_reactions={PlaceObj('UnitReaction', {Event="OnBeginTurn", Handler=function(self, target)
        target:AddStatusEffect("AI_AdditionalAP")
    end})}}

