---
--- Represents an AI taunt counter effect that is applied to a character.
--- This effect is automatically removed at the start of the character's turn.
--- The effect has a maximum of 3 stacks and is removed when the combat ends.
---
--- @class AITauntCounter
--- @field object_class string The class name of the effect object
--- @field unit_reactions table A table of unit reactions associated with the effect
--- @field max_stacks integer The maximum number of stacks the effect can have
--- @field RemoveOnEndCombat boolean Whether the effect is removed when the combat ends
-- ========== GENERATED BY CharacterEffectCompositeDef Editor DO NOT EDIT MANUALLY! ==========
UndefineClass('AITauntCounter')
DefineClass.AITauntCounter = {__parents={"CharacterEffect"}, __generated_by_class="CharacterEffectCompositeDef",

    object_class="CharacterEffect",
    unit_reactions={PlaceObj('UnitReaction', {Event="OnBeginTurn", Handler=function(self, target)
        target:RemoveStatusEffect(self.class, "all")
    end})}, max_stacks=3, RemoveOnEndCombat=true}

