if not config.Mods then return end

DefineModItemPreset("SetpiecePrg", { EditorSubmenu = "Campaign & Maps", EditorName = "Setpiece", ModItemDescription = Untranslated("<u(id)> - <opt(Map)>") })

AppendClass.ModItemSetpiecePrg = {
	__parents = { "ModItemMapPatch" },
	properties = {
		{ category = "Map", id = "Help", editor = false }, -- remove prop from ModItemMapPatch
		{ category = "Map", id = "Map", editor = "choice", default = false, items = function() return GetPatchableMaps() end, read_only = IsChangingMap },
		{ category = "Map", id = "PlaceMarkers", editor = "buttons", default = "", --overwrite place marker buttons to modify their no_edit funcs
			buttons = function() return table.map(ClassLeafDescendantsList("SetpieceMarker"), function(class)
				return { name = "Place " .. g_Classes[class].DisplayName, func = SetpieceMarkerPlaceButton, param = class }
			end) end,
			no_edit = function(self) return not self.Map or self.Map ~= CurrentMap or not editor.IsModdingEditor() or IsChangingMap() end,
		},
		{ id = "mapName", default = false, no_edit = true, editor = "text" },
	},
	Documentation = "Creates a new setpiece which allows setting up a sequence of commands controlling various things such as actors behavior, camera behavior, animation, etc. Cut-scenes are usually created via setpieces.",
	TestDescription = "Starts the setpiece."
}

ModItemSetpiecePrg.__toluacode = ModItemUsingFiles.__toluacode
ModItemSetpiecePrg.Documentation = SetpiecePrg.Documentation ..
	"\n\nA Setpiece mod item will allow you to edit the map, and store your changes as a <style GedHighlight>map patch</style>."

---
--- Overrides the `ModItemMapPatch:GetModItemDescription()` function to restore the default behavior.
---
--- @return string The mod item description.
---
function ModItemSetpiecePrg:GetModItemDescription()
	-- override ModItemMapPatch:GetModItemDescription() to restore the default behavior
	return self.ModItemDescription
end

---
--- Generates a unique map name for the setpiece and creates the destination folder for the map patch.
---
--- This function is called when a new setpiece mod item is created in the editor.
---
--- @return void
---
function ModItemSetpiecePrg:OnEditorNew()
	self:GenerateMapName()
	AsyncCreatePath(self:GetDestinationFolder())
	self.Map = false end

---
--- Deletes the destination folder for the setpiece map patch when the mod item is deleted from the editor.
---
--- This function is called when a setpiece mod item is deleted from the editor.
---
--- @return void
---
function ModItemSetpiecePrg:OnEditorDelete()
	AsyncDeletePath(self:GetDestinationFolder())
end

---
--- Returns a message to display in the editor's status bar for this setpiece map patch.
---
--- @return string The editor message to display.
---
function ModItemSetpiecePrg:GetEditorMessage()
	return string.format("Setpiece map patch in mod: %s", Literal(self.mod.title)) -- appears in editor's status bar
end

---
--- Checks if the setpiece has a valid map reference.
---
--- @return string|nil The error message if the map reference is missing, otherwise nil.
---
function ModItemSetpiecePrg:GetError()
	if not self.Map or self.Map == "" then
		return "The setpiece requires a map reference."
	end
end

---
--- Tests the mod item setpiece.
---
--- This function is called when the user wants to test the mod item setpiece. It first checks if there are any errors with the setpiece, and if so, displays a warning message to the user. If there are no errors, it calls the `SetpiecePrg.Test()` function to actually test the setpiece.
---
--- @param ged EditorGlobalData The global editor data.
--- @return void
---
function ModItemSetpiecePrg:TestModItem(ged)
	if self:GetError() then
		ged:ShowMessage("Warning", "Resolve errors before trying to test.")
		return
	end
	SetpiecePrg.Test(self, ged)
end

---
--- Returns a list of resources affected by this mod item setpiece.
---
--- This function aggregates the affected resources from the `ModItemMapPatch` and `ModItemPreset` components of the setpiece.
---
--- @return table The list of affected resources.
---
function ModItemSetpiecePrg:GetAffectedResources()
	local affected_resources = {}
	table.iappend(affected_resources, ModItemMapPatch.GetAffectedResources(self))
	table.iappend(affected_resources, ModItemPreset.GetAffectedResources(self))
	return affected_resources
end

---
--- Generates a unique map name for the mod item setpiece.
---
--- The map name is generated by concatenating the setpiece ID with a randomly generated ID. If the generated map name already exists, a new one is generated until a unique name is found.
---
--- @return void
---
function ModItemSetpiecePrg:GenerateMapName()
	self.mapName = self.id .. "_" .. ModDef.GenerateId()
	while io.exists(self:GetDestinationFolder()) do
		self.mapName = self.id .. "_" .. ModDef.GenerateId()
	end
end

---
--- Returns the destination subfolder for the mod item setpiece.
---
--- The destination subfolder is constructed by concatenating "MapPatches/SetPieces/" with the map name of the setpiece.
---
--- @return string The destination subfolder for the mod item setpiece.
---
function ModItemSetpiecePrg:GetDestinationSubFolder()
	return "MapPatches/SetPieces/" .. self.mapName
end

---
--- Returns the full destination folder path for the mod item setpiece.
---
--- The destination folder path is constructed by concatenating the mod's content path with the destination subfolder for the setpiece.
---
--- @return string The full destination folder path for the mod item setpiece.
---
function ModItemSetpiecePrg:GetDestinationFolder()
	return SlashTerminate(self.mod.content_path) .. self:GetDestinationSubFolder()
end

---
--- Returns the file name for the mod item setpiece.
---
--- If the setpiece has a companion file or the `GetCompanionFilesList` function is not the same as the `Preset.GetCompanionFilesList` function, this function generates a file name by concatenating the destination subfolder and the setpiece ID (with any invalid characters replaced by underscores).
---
--- @param name string (optional) The name to use for the file. If not provided, the setpiece ID will be used.
--- @return string The file name for the mod item setpiece.
---
function ModItemSetpiecePrg:GetCodeFileName(name)
	if self.HasCompanionFile or self.GetCompanionFilesList ~= Preset.GetCompanionFilesList then
		name = name or self.id
		return name and name ~= "" and
			string.format("%s/%s.lua", self:GetDestinationSubFolder(), name:gsub('[/?<>\\:*|"]', "_"))
	end
end

---
--- Gets the contents of the files associated with the ModItemSetpiecePrg.
---
--- This function calls ModItemMapPatch.GetFilesContents to get the contents of the files, and then adds two additional fields to the returned table:
--- - `prev_dest_folder`: The destination folder of the previous map patch.
--- - `prev_map`: The previous map.
---
--- @param filesList table The list of files to get the contents of.
--- @return table The contents of the files, with the additional `prev_dest_folder` and `prev_map` fields.
---
function ModItemSetpiecePrg:GetFilesContents(filesList)
	local files = ModItemMapPatch.GetFilesContents(self)
	files["prev_dest_folder"] = self:GetDestinationFolder()
	files["prev_map"] = self.Map
	return files
end

---
--- Resolves any conflicts that may arise when pasting files for the mod item setpiece.
---
--- This function updates the `filename` property of each file in the `CopyFiles` table to use the current destination folder for the mod item setpiece, rather than the previous destination folder.
---
--- It also updates the `Map` property of the `ModItemSetpiecePrg` instance to the `prev_map` value from the `CopyFiles` table.
---
--- @param ged table The `ged` parameter is not used in this function.
---
function ModItemSetpiecePrg:ResolvePasteFilesConflicts(ged)
	self.Map = self.CopyFiles.prev_map
	for _, copy_file in ipairs(self.CopyFiles) do
		copy_file.filename = copy_file.filename:gsub(self.CopyFiles.prev_dest_folder, self:GetDestinationFolder())
	end
end