-- ========== GENERATED BY ExtrasGen Editor (Ctrl-Alt-G) DO NOT EDIT MANUALLY! ==========

rawset(_G, 'ExtrasGenPrgs', rawget(_G, 'ExtrasGenPrgs') or {})
---
--- Generates a set of guides between slabs in the editor.
---
--- @param seed number|nil The seed to use for the random number generator. If not provided, a random seed will be used.
--- @param initial_selection table|nil The initial selection to use as the starting point for the guides. If not provided, the current editor selection will be used.
--- @return table The guides that were generated.
---
ExtrasGenPrgs.BetweenSlabs = function(seed, initial_selection)
	local li = { id = "BetweenSlabs" }
	initial_selection = initial_selection or editor.GetSel()
	local rand = BraidRandomCreate(seed or AsyncRand())
	local _, guides
	prgdbg(li, 1, 1) _, guides = sprocall(PlaceGuidesBetweenSlabs.Exec, PlaceGuidesBetweenSlabs, initial_selection, guides)
	prgdbg(li, 1, 2) sprocall(SelectInEditor.Exec, SelectInEditor, guides, true, true)
end