-- ========== GENERATED BY ExtrasGen Editor (Ctrl-Alt-G) DO NOT EDIT MANUALLY! ==========

rawset(_G, 'ExtrasGenPrgs', rawget(_G, 'ExtrasGenPrgs') or {})
---
--- Generates a "Bottom Up" layout for room guides in the editor.
---
--- @param seed number|nil The random seed to use for guide placement. If not provided, a random seed will be used.
--- @param initial_selection table|nil The initial selection in the editor to use as the starting point for guide placement. If not provided, the current editor selection will be used.
--- @return nil
---
ExtrasGenPrgs.BottomUp = function(seed, initial_selection)
	local li = { id = "BottomUp" }
	initial_selection = initial_selection or editor.GetSel()
	local rand = BraidRandomCreate(seed or AsyncRand())
	local _, guides
	prgdbg(li, 1, 1) _, guides = sprocall(PlaceRoomGuides.Exec, PlaceRoomGuides, initial_selection, guides, "Wall exterior", true, true, true, true, true, true, "Bottom", 1, 0, 0, "Inwards (wall)")
	prgdbg(li, 1, 2) sprocall(SelectInEditor.Exec, SelectInEditor, guides, true, true)
end