-- ========== GENERATED BY ExtrasGen Editor (Ctrl-Alt-G) DO NOT EDIT MANUALLY! ==========

rawset(_G, 'ExtrasGenPrgs', rawget(_G, 'ExtrasGenPrgs') or {})
---
--- Deletes room guides from the initial selection.
---
--- @param seed number|nil The seed to use for the random number generator. If not provided, a random seed will be used.
--- @param initial_selection table|nil The initial selection to use. If not provided, the current editor selection will be used.
---
--- @return nil
ExtrasGenPrgs.DeleteGuides = function(seed, initial_selection)
	local li = { id = "DeleteGuides" }
	initial_selection = initial_selection or editor.GetSel()
	local rand = BraidRandomCreate(seed or AsyncRand())
	prgdbg(li, 1, 1) sprocall(RemoveRoomGuides.Exec, RemoveRoomGuides, initial_selection)
end