-- ========== GENERATED BY ExtrasGen Editor (Ctrl-Alt-G) DO NOT EDIT MANUALLY! ==========

rawset(_G, 'ExtrasGenPrgs', rawget(_G, 'ExtrasGenPrgs') or {})
---
--- Generates a set of colonial-style socles along a given selection.
---
--- @param seed number|nil The random seed to use for generation. If not provided, a random seed will be used.
--- @param initial_selection table|nil The initial selection to use as a starting point. If not provided, the current editor selection will be used.
---
--- @return nil
---
ExtrasGenPrgs.LayColonialSocles = function(seed, initial_selection)
	local li = { id = "LayColonialSocles" }
	initial_selection = initial_selection or editor.GetSel()
	local rand = BraidRandomCreate(seed or AsyncRand())
	prgdbg(li, 1, 1) sprocall(LaySlabsAlongGuides.Exec, LaySlabsAlongGuides, rand, initial_selection, nil, true, true, true, 0, true, 1, 0, 0, true, true, {PlaceObj('PlaceObjectData', {EditorClass = "WallDec_Colonial_Socle_Corner_01",}),}, false, {PlaceObj('PlaceObjectData', {EditorClass = "WallDec_Colonial_Socle_Body_01",}),}, false, false, true, true, false, false, 0, 0, false, false)
end