-- ========== GENERATED BY ExtrasGen Editor (Ctrl-Alt-G) DO NOT EDIT MANUALLY! ==========

rawset(_G, 'ExtrasGenPrgs', rawget(_G, 'ExtrasGenPrgs') or {})
---
--- Generates a colonial edge light decoration using the LaySlabsAlongGuides function.
---
--- @param seed number|nil The random seed to use for generation. If not provided, a random seed will be used.
--- @param initial_selection table|nil The initial selection to use for the generation. If not provided, the current editor selection will be used.
---
ExtrasGenPrgs.LayColonialEdge_04_Light = function(seed, initial_selection)
	local li = { id = "LayColonialEdge_04_Light" }
	initial_selection = initial_selection or editor.GetSel()
	local rand = BraidRandomCreate(seed or AsyncRand())
	prgdbg(li, 1, 1) sprocall(LaySlabsAlongGuides.Exec, LaySlabsAlongGuides, rand, initial_selection, nil, true, true, true, 0, true, 1, 0, 0, true, true, {PlaceObj('PlaceObjectData', {EditorClass = "WallDec_Colonial_Column_Bottom_07",Rotate = 5400,}),}, false, {PlaceObj('PlaceObjectData', {EditorClass = "WallDec_Colonial_Column_Body_04",Rotate = 5400,}),}, {PlaceObj('PlaceObjectData', {EditorClass = "WallDec_Colonial_Column_Top_04",Rotate = 5400,}),}, false, false, false, true, true, 0, 0, false, false)
end