-- ========== GENERATED BY ExtrasGen Editor (Ctrl-Alt-G) DO NOT EDIT MANUALLY! ==========

rawset(_G, 'ExtrasGenPrgs', rawget(_G, 'ExtrasGenPrgs') or {})
---
--- Generates a colonial frieze interior decoration using the ExtrasGen system.
---
--- @param seed number|nil The random seed to use for generating the decoration. If not provided, a random seed will be used.
--- @param initial_selection table|nil The initial selection to use as a starting point for the decoration. If not provided, the current editor selection will be used.
---
--- @return nil
---
ExtrasGenPrgs.LayColonialFriezeInterior = function(seed, initial_selection)
	local li = { id = "LayColonialFriezeInterior" }
	initial_selection = initial_selection or editor.GetSel()
	local rand = BraidRandomCreate(seed or AsyncRand())
	prgdbg(li, 1, 1) sprocall(MoveSizeGuides.Exec, MoveSizeGuides, initial_selection, 700, -700, "m", 0, "m", 0, false)
	prgdbg(li, 1, 2) sprocall(LaySlabsAlongGuides.Exec, LaySlabsAlongGuides, rand, initial_selection, nil, true, true, true, 0, true, 1, 0, 0, true, false, false, false, {PlaceObj('PlaceObjectData', {EditorClass = "WallDec_Colonial_Frieze_Body_01",}),}, false, false, true, true, false, false, 0, 0, false, false)
	prgdbg(li, 1, 3) sprocall(MoveSizeGuides.Exec, MoveSizeGuides, initial_selection, 700, 700, "m", 0, "m", 0, false)
end