-- ========== GENERATED BY ExtrasGen Editor (Ctrl-Alt-G) DO NOT EDIT MANUALLY! ==========

rawset(_G, 'ExtrasGenPrgs', rawget(_G, 'ExtrasGenPrgs') or {})
---
--- Generates a colonial column using the LaySlabsAlongGuides function.
---
--- @param seed number|nil The random seed to use for generating the column. If not provided, a random seed will be used.
--- @param initial_selection table|nil The initial selection to use for the column generation. If not provided, the current editor selection will be used.
---
--- @return table The generated column object.
---
ExtrasGenPrgs.LayColonialColumn_01 = function(seed, initial_selection)
	local li = { id = "LayColonialColumn_01" }
	initial_selection = initial_selection or editor.GetSel()
	local rand = BraidRandomCreate(seed or AsyncRand())
	prgdbg(li, 1, 1) sprocall(LaySlabsAlongGuides.Exec, LaySlabsAlongGuides, rand, initial_selection, nil, true, true, true, 0, true, 1, 0, 0, true, true, {PlaceObj('PlaceObjectData', {EditorClass = "Column_Colonial_Bottom_01",}),}, false, {PlaceObj('PlaceObjectData', {EditorClass = "Column_Colonial_Body_01",}),}, {PlaceObj('PlaceObjectData', {EditorClass = "Column_Colonial_Top_01",}),}, false, false, false, true, true, 0, 0, false, false)
end