-- ========== GENERATED BY ExtrasGen Editor (Ctrl-Alt-G) DO NOT EDIT MANUALLY! ==========

rawset(_G, 'ExtrasGenPrgs', rawget(_G, 'ExtrasGenPrgs') or {})
---
--- Generates a set of dirt decals along a guide selection.
---
--- @param seed number|nil The random seed to use for the decal placement. If not provided, a random seed will be used.
--- @param initial_selection table|nil The initial selection to use as the guide for the decal placement. If not provided, the current editor selection will be used.
---
ExtrasGenPrgs.LayDirt = function(seed, initial_selection)
	local li = { id = "LayDirt" }
	initial_selection = initial_selection or editor.GetSel()
	local rand = BraidRandomCreate(seed or AsyncRand())
	prgdbg(li, 1, 1) sprocall(LayDecalsAlongGuide.Exec, LayDecalsAlongGuide, rand, initial_selection, nil, {PlaceObj('PlaceObjectDataDecal', {EditorClass = "DecWallDirt_03",FlipVertically = true,MoveDownPercent = 5,ScaleAfterPlace = 108,}),PlaceObj('PlaceObjectDataDecal', {EditorClass = "DecWallDirt_06",MoveDownPercent = 50,}),PlaceObj('PlaceObjectDataDecal', {EditorClass = "DecWallDirt_07",MoveDownPercent = 50,}),}, false)
end