-- ========== GENERATED BY ExtrasGen Editor (Ctrl-Alt-G) DO NOT EDIT MANUALLY! ==========

rawset(_G, 'ExtrasGenPrgs', rawget(_G, 'ExtrasGenPrgs') or {})
---
--- Generates a set of wall leak decals along a guide selection.
---
--- @param seed number|nil The random seed to use for generating the decals. If not provided, a random seed will be used.
--- @param initial_selection table|nil The initial selection to use as the guide for the decals. If not provided, the current editor selection will be used.
---
ExtrasGenPrgs.LayLeaks = function(seed, initial_selection)
	local li = { id = "LayLeaks" }
	initial_selection = initial_selection or editor.GetSel()
	local rand = BraidRandomCreate(seed or AsyncRand())
	prgdbg(li, 1, 1) sprocall(LayDecalsAlongGuide.Exec, LayDecalsAlongGuide, rand, initial_selection, nil, {PlaceObj('PlaceObjectDataDecal', {EditorClass = "DecWallLeak_01",}),PlaceObj('PlaceObjectDataDecal', {EditorClass = "DecWallLeak_02",}),PlaceObj('PlaceObjectDataDecal', {EditorClass = "DecWallLeak_03",}),PlaceObj('PlaceObjectDataDecal', {EditorClass = "DecWallLeak_04",}),}, false)
end