-- ========== GENERATED BY ExtrasGen Editor (Ctrl-Alt-G) DO NOT EDIT MANUALLY! ==========

rawset(_G, 'ExtrasGenPrgs', rawget(_G, 'ExtrasGenPrgs') or {})
---
--- Generates a platform outside the map using the LaySlabsAlongGuides function.
---
--- @param seed number|nil The seed to use for the random number generator. If not provided, a random seed will be used.
--- @param initial_selection table|nil The initial selection to use for the operation. If not provided, the current editor selection will be used.
---

ExtrasGenPrgs.LayPlatformOutside = function(seed, initial_selection)
	local li = { id = "LayPlatformOutside" }
	initial_selection = initial_selection or editor.GetSel()
	local rand = BraidRandomCreate(seed or AsyncRand())
	prgdbg(li, 1, 1) sprocall(LaySlabsAlongGuides.Exec, LaySlabsAlongGuides, rand, initial_selection, nil, true, false, false, 0, true, 1, 0, 0, true, false, {PlaceObj('PlaceObjectData', {EditorClass = "FloorSlab",}),}, false, {PlaceObj('PlaceObjectData', {EditorClass = "FloorSlab",}),}, false, false, false, false, false, false, 0, 0, true, false)
end