-- ========== GENERATED BY ExtrasGen Editor (Ctrl-Alt-G) DO NOT EDIT MANUALLY! ==========

rawset(_G, 'ExtrasGenPrgs', rawget(_G, 'ExtrasGenPrgs') or {})
---
--- Generates a set of rust decals along a guide selection.
---
--- @param seed number|nil The seed to use for the random number generator. If not provided, a random seed will be used.
--- @param initial_selection table|nil The initial selection to use as the guide. If not provided, the current editor selection will be used.
---
ExtrasGenPrgs.LayRust_01 = function(seed, initial_selection)
	local li = { id = "LayRust_01" }
	initial_selection = initial_selection or editor.GetSel()
	local rand = BraidRandomCreate(seed or AsyncRand())
	prgdbg(li, 1, 1) sprocall(LayDecalsAlongGuide.Exec, LayDecalsAlongGuide, rand, initial_selection, nil, {PlaceObj('PlaceObjectDataDecal', {EditorClass = "DecWallRust_01",MoveDownPercent = 15,Scale = 150,}),}, false)
end