-- ========== GENERATED BY ExtrasGen Editor (Ctrl-Alt-G) DO NOT EDIT MANUALLY! ==========

rawset(_G, 'ExtrasGenPrgs', rawget(_G, 'ExtrasGenPrgs') or {})
--- Generates a wall layout using the LaySlabsAlongGuides function.
---
--- @param seed number|nil The seed to use for the random number generator. If not provided, a random seed will be used.
--- @param initial_selection table|nil The initial selection to use for the wall layout. If not provided, the current editor selection will be used.
--- @return table The generated wall layout.
ExtrasGenPrgs.LayWall = function(seed, initial_selection)
	local li = { id = "LayWall" }
	initial_selection = initial_selection or editor.GetSel()
	local rand = BraidRandomCreate(seed or AsyncRand())
	prgdbg(li, 1, 1) sprocall(LaySlabsAlongGuides.Exec, LaySlabsAlongGuides, rand, initial_selection, nil, true, true, false, 0, true, 1, 0, 0, true, false, {PlaceObj('PlaceObjectData', {EditorClass = "RoomCorner",}),}, false, {PlaceObj('PlaceObjectData', {EditorClass = "WallSlab",}),}, false, false, true, false, false, false, 0, 0, false, false)
end