-- ========== GENERATED BY ExtrasGen Editor (Ctrl-Alt-G) DO NOT EDIT MANUALLY! ==========

rawset(_G, 'ExtrasGenPrgs', rawget(_G, 'ExtrasGenPrgs') or {})
---
--- Generates a set of room guides for the current editor selection, with the edges of the guides pointing inwards towards the center of the room.
---
--- @param seed number|nil The random seed to use for generating the guides. If not provided, a random seed will be used.
--- @param initial_selection table|nil The initial editor selection to use as the basis for the guides. If not provided, the current editor selection will be used.
---
ExtrasGenPrgs.RoofEdgesInwardsAcross = function(seed, initial_selection)
	local li = { id = "RoofEdgesInwardsAcross" }
	initial_selection = initial_selection or editor.GetSel()
	local rand = BraidRandomCreate(seed or AsyncRand())
	local _, guides
	prgdbg(li, 1, 1) _, guides = sprocall(PlaceRoomGuides.Exec, PlaceRoomGuides, initial_selection, guides, "Roof", false, true, true, true, true, false, "Both", 1, 0, 0, "Inwards (wall)")
	prgdbg(li, 1, 2) sprocall(SelectInEditor.Exec, SelectInEditor, guides, true, true)
end